# Generated by Django 5.2.8 on 2025-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=200)),
                ('company_logo_url', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('job_description', models.TextField()),
                ('stars', models.IntegerField()),
                ('skills', models.JSONField()),
                ('life_at_company_description', models.TextField()),
                ('life_at_company_image_url', models.URLField()),
            ],
        ),
    ]
