# Generated by Django 5.2.8 on 2025-12-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('IT', 'Internship'), ('FR', 'Freelance')], default='FT', max_length=2),
        ),
    ]
