# Generated by Django 5.2.8 on 2025-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_job_company_logo_url_alter_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='life_at_company_image_url',
            field=models.CharField(max_length=500),
        ),
    ]
